#!/bin/sh
#
# makesrcdist - make a source distribution of htmlcss.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating htmlcss-$version.tar.gz...
git archive --format tar --prefix=htmlcss-$version/ HEAD | gzip -v9 >htmlcss-$version.tar.gz
gpg --detach-sign htmlcss-$version.tar.gz

