name: Build
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout HTMLCSS sources
      uses: actions/checkout@v4
    - name: Update Build Environment
      run: sudo apt-get update --fix-missing -y
    - name: Install Prerequisites
      run: sudo apt-get install -y cppcheck zlib1g-dev
    - name: Configure HTMLCSS
      run: ./configure --enable-debug --enable-sanitizer --enable-maintainer
    - name: Make HTMLCSS
      run: make
    - name: Test HTMLCSS
      env:
        ASAN_OPTIONS: leak_check_at_exit=false
      run: make test
    - name: Run Clang Static Analyzer
      run: make CC=clang "GHA_ERROR=::error::" clang
    - name: Run cppcheck
      run: make "GHA_ERROR=::error::" cppcheck

  build-macos:

    runs-on: macos-latest

    steps:
    - name: Checkout HTMLCSS sources
      uses: actions/checkout@v4
    - name: Configure HTMLCSS
      run: ./configure --enable-debug --enable-sanitizer --enable-maintainer
    - name: Make HTMLCSS
      run: make
    - name: Test HTMLCSS
      env:
        ASAN_OPTIONS: leak_check_at_exit=false
      run: make test
    - name: Run Clang Static Analyzer
      run: make CC=clang "GHA_ERROR=::error::" clang

#  build-windows:
#
#   runs-on: windows-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: setup-msbuild
#      uses: microsoft/setup-msbuild@v1.0.2
#    - name: nuget restore
#      run: nuget restore pdfio.sln
#    - name: msbuild
#      run: msbuild pdfio.sln
